# Common configuration.
AllCops:
  # Include common Ruby source files.
  Include:
    - '**/*.gemspec'
    - '**/*.podspec'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/*.opal'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Podfile'
    - '**/Thorfile'
    - '**/Vagrantfile'
    - '**/Berksfile'
    - '**/Cheffile'
    - '**/Vagabondfile'
  Exclude:
    - 'vendor/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'Gemfile*'
    - 'bin/**/*'
    - 'Guardfile*'

  # Cop names are not displayed in offense messages by default. Change behavior
  # by overriding DisplayCopNames, or by giving the -D/--display-cop-names
  # option.
  DisplayCopNames: true
  # Style guide URLs are not displayed in offense messages by default. Change
  # behavior by overriding DisplayStyleGuide, or by giving the
  # -S/--display-style-guide option.
  DisplayStyleGuide: true
  # Additional cops that do not reference a style guide rule may be enabled by
  # default. Change behavior by overriding StyleGuideCopsOnly, or by giving
  # the --only-guide-cops option.
  StyleGuideCopsOnly: false
  # All cops except the ones in disabled.yml are enabled by default. Change
  # this behavior by overriding DisabledByDefault. When DisabledByDefault is
  # true, all cops in the default configuration are disabled, and and only cops
  # in user configuration are enabled. This makes cops opt-in instead of
  # opt-out. Note that when DisabledByDefault is true, cops in user
  # configuration will be enabled even if they don't set the Enabled parameter.
  DisabledByDefault: false
  # Enables the result cache if true. Can be overridden by the --cache command
  # line option.
  UseCache: true
  # Threshold for how many files can be stored in the result cache before some
  # of the files are automatically removed.
  MaxFilesInCache: 20000
  # The cache will be stored in "rubocop_cache" under this directory. The name
  # "/tmp" is special and will be converted to the system temporary directory,
  # which is "/tmp" on Unix-like systems, but could be something else on other
  # systems.
  CacheRootDirectory: /tmp

Metrics/LineLength:
  Max: 80

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/BlockComments:
  Enabled: false
